@WebApi__HostAddress = http://localhost:5023

GET {{WebApi__HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{WebApi__HostAddress}}/api/regions/
Content-Type: application/json

{
  "code": "TR",
  "name": "Testing Region",
  "regionImageUrl": "www.google.com"
}
###